In [84]:
#Data.csv

In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [86]:
data = pd.read_csv("Data.csv")

In [87]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [88]:
x=data.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [89]:
y = data.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [90]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan,strategy='mean')
imp = imp.fit(x[:,1:3])
x[:,1:3] = imp.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [91]:
x1=data.iloc[:,0:3]
y1=data.iloc[:,3]

In [92]:
x1

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [93]:
y1

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [94]:
from sklearn.impute import SimpleImputer
impdf = SimpleImputer(missing_values=np.nan,strategy='mean')
impdf = impdf.fit(x[:,1:3])
impdf

SimpleImputer()

In [95]:
x1.iloc[:,1]

0    44.0
1    27.0
2    30.0
3    38.0
4    40.0
5    35.0
6     NaN
7    48.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [96]:
x1.iloc[:,1:3] = impdf.transform(x1.iloc[:,1:3])
x1

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [97]:
x_labelencoded = x[:,0]
x_labelencoded

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [98]:
from sklearn.preprocessing import OneHotEncoder
onehotenc = OneHotEncoder()
x_columnsencoded = onehotenc.fit_transform(x[:,0].reshape(-1,1)).toarray()
x_columnsencoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [99]:
x[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [100]:
x = np.delete(x,[0],1)
x_columnsencoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [101]:
x1 = pd.DataFrame(x_columnsencoded)
x2 = pd.DataFrame(x)
x1

0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0
5  1.0  0.0  0.0
6  0.0  0.0  1.0
7  1.0  0.0  0.0
8  0.0  1.0  0.0
9  1.0  0.0  0.0

In [102]:
x2

0             1
0       44.0       72000.0
1       27.0       48000.0
2       30.0       54000.0
3       38.0       61000.0
4       40.0  63777.777778
5       35.0       58000.0
6  38.777778       52000.0
7       48.0       79000.0
8       50.0       83000.0
9       37.0       67000.0

In [103]:
x = pd.concat([x1,x2],axis=1)
type(x)
x

0    1    2          0             1
0  1.0  0.0  0.0       44.0       72000.0
1  0.0  0.0  1.0       27.0       48000.0
2  0.0  1.0  0.0       30.0       54000.0
3  0.0  0.0  1.0       38.0       61000.0
4  0.0  1.0  0.0       40.0  63777.777778
5  1.0  0.0  0.0       35.0       58000.0
6  0.0  0.0  1.0  38.777778       52000.0
7  1.0  0.0  0.0       48.0       79000.0
8  0.0  1.0  0.0       50.0       83000.0
9  1.0  0.0  0.0       37.0       67000.0

In [104]:
x=x.iloc[:,:].values
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [105]:
from sklearn.preprocessing import LabelEncoder
lencoder = LabelEncoder()
y = lencoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [106]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.8, random_state = 42)

In [107]:
x_train

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [108]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0])

In [109]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

In [110]:
x_train

array([[ 1.        , -0.57735027, -0.57735027, -0.7529426 , -0.62603778],
       [ 1.        , -0.57735027, -0.57735027,  1.00845381,  1.01304295],
       [ 1.        , -0.57735027, -0.57735027,  1.79129666,  1.83258331],
       [-1.        ,  1.73205081, -0.57735027, -1.73149616, -1.09434656],
       [ 1.        , -0.57735027, -0.57735027, -0.36152118,  0.42765698],
       [-1.        ,  1.73205081, -0.57735027,  0.22561096,  0.05040824],
       [-1.        , -0.57735027,  1.73205081, -0.16581046, -0.27480619],
       [-1.        , -0.57735027,  1.73205081, -0.01359102, -1.32850095]])

In [111]:
x_test

array([[-1.        ,  1.73205081, -0.57735027,  2.18271808,  2.30089209],
       [-1.        , -0.57735027,  1.73205081, -2.3186283 , -1.79680973]])